src/java/entity/Book.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package entity;

import dao.CategoryDao;
import java.util.List;
import lombok.Builder;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;


/**
 *
 * @author hoang
 */
@Getter
@Setter
@Builder
@ToString
public class Book {
    private int id;
    private String name;
    private int authorId;
    private int translatorId;
    private int totalChap;
    private int appear;
    private int totalView;
    private int totalLike;
    private int totalFollow;
    private int totalComment;
    private String status;
    private String description;
    private String imgName;
    private String latestUpdate;
    private String bookmarkedChapter;
    private int bookmarkedChapterId;
    
    public Book() {
    }

    public Book(int id, String name, int authorId, int translatorId, int totalChap, int appear, int totalView, int totalLike, int totalFollow, int totalComment, String status, String description, String imgName, String latestUpdate) {
        this.id = id;
        this.name = name;
        this.authorId = authorId;
        this.translatorId = translatorId;
        this.totalChap = totalChap;
        this.appear = appear;
        this.totalView = totalView;
        this.totalLike = totalLike;
        this.totalFollow = totalFollow;
        this.totalComment = totalComment;
        this.status = status;
        this.description = description;
        this.imgName = imgName;
        this.latestUpdate = latestUpdate;
    }
    public Book(int id, String name, int authorId, int translatorId, int totalChap, int appear, int totalView, int totalLike, int totalFollow, int totalComment, String status, String description, String imgName, String latestUpdate,String bookmarkedChapter, int bookmarkedChapterId){
        this.id = id;
        this.name = name;
        this.authorId = authorId;
        this.translatorId = translatorId;
        this.totalChap = totalChap;
        this.appear = appear;
        this.totalView = totalView;
        this.totalLike = totalLike;
        this.totalFollow = totalFollow;
        this.totalComment = totalComment;
        this.status = status;
        this.description = description;
        this.imgName = imgName;
        this.latestUpdate = latestUpdate;
        this.bookmarkedChapter = bookmarkedChapter;
        this.bookmarkedChapterId = bookmarkedChapterId;
    }
    
    public List<Category> getAllCategory(){
        List<Category> ls = new CategoryDao().getAllWithBookId(id);
        return ls;
    }
    public String getBookMarkChapter(){
        return null;
    }
}

src/java/entity/Comment.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package entity;

import java.sql.Date;
import java.util.Calendar;
import lombok.Builder;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 *
 * @author hoang
 */
@Getter
@Setter
@Builder
@ToString
public class Comment implements Comparable<Comment> {

    private int commentId;
    private int bookId;
    private int chapterId;
    private Account account;
    private String content;
    private Date date;

    @Override
    public int compareTo(Comment t) {
        if (this.getPostTime().equals("New!") && t.getPostTime().equals("New!")) {
            if(this.commentId>t.getCommentId())return -1;
            return 1;
        }

        return -this.date.compareTo(t.getDate());
    }

    public String getPostTime() {
        Calendar latestChapterDate = Calendar.getInstance();
        latestChapterDate.setTime(date);
        Calendar cur = Calendar.getInstance();
        long dif = (long) ((cur.getTimeInMillis() - latestChapterDate.getTimeInMillis()) / 999.999);

        int year = (int) (dif / 60 / 60 / 24 / 365);
        if (year > 0) {
            if (year > 1) {
                return year + " years";
            } else {
                return "1 year";
            }
        }
        int month = (int) (dif / 60 / 60 / 24 / 30);
        if (month > 0) {
            if (month > 1) {
                return month + " months";
            } else {
                return "1 month";
            }
        }
        int day = (int) (dif / 60 / 60 / 24);
        if (day > 0) {
            if (day > 1) {
                return day + " days";
            } else {
                return "1 day";
            }
        }
//        int hour = (int) (dif/60/60);
//        if(hour > 0){
//            if(hour>1){
//                return hour + " hours";
//            }
//            else{
//                return "1 hour";
//            }
//        }
//        int minute = (int) (dif/60);
//        if(minute > 0){
//            if(minute>1){
//                return minute+" minutes";
//            }
//            else{
//                return "1 minutes";
//            }
//        }
        return "New!";
    }
}

src/java/controller/BookServlet.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controller;

import dao.BookDao;
import dao.CategoryDao;
import dao.HistoryDao;
import dao.NotificationDao;
import entity.Book;
import entity.Category;
import entity.History;
import entity.Notification;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.List;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

/**
 *
 * @author hoang
 */
@WebServlet(name = "BookServlet", urlPatterns = {"/BookServlet"})
public class BookServlet extends HttpServlet {

    /**
     * Processes requests for both HTTP <code>GET</code> and <code>POST</code>
     * methods.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    protected void processRequest(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");
        try {

            List<Book> ls = new BookDao().getAllNewest();

            List<Category> lsCategory = new CategoryDao().getAll();
            HttpSession session = request.getSession(false);
            List<History> lsHistory = new HistoryDao().getBook_DateHistoryWithAccountId(1);
            boolean check = false;
            if (session != null) {
                if (session.getAttribute("user") != null) {
                    lsHistory = new HistoryDao().getBook_DateHistoryWithAccountId((int) session.getAttribute("accountId"));
                }

            }

            int bookIdArray[] = new int[lsHistory.size()];
            for (History i : lsHistory) {
                bookIdArray[lsHistory.indexOf(i)] = i.getBookId();
            }
            List<Book> lsBookHistory = new BookDao().getAllWithIds(bookIdArray);
//            ls.forEach(System.out::println);
            List<Book> lsBookTopView = new BookDao().getTopView();

            int page = 1;

            if (request.getParameter("page") != null) {
                page = Integer.parseInt(request.getParameter("page"));
                switch (request.getParameter("action")) {
                    case ("-1"):
                        page -= 1;
                        break;
                    case ("1"):
                        page = 1;
                        break;
                    case ("2"):
                        page = 2;
                        break;
                    case ("3"):
                        page = 3;
                        break;
                    case ("-2"):
                        page += 1;
                        break;
                }
            }
            int bookNum = 12;
            ls = new BookDao().getAllPagnition(page, bookNum);
            List<Notification> lsNotification = new ArrayList();
            if (session != null) {
                if (session.getAttribute("accountId") != null) {
                    lsNotification = new NotificationDao().getAllWithAccount((int) session.getAttribute("accountId"));
                    request.setAttribute("lsNotification", lsNotification);
                }
            }

            request.setAttribute("page", page);
            request.setAttribute("lsTopView", lsBookTopView);
            request.setAttribute("lsHistory", lsHistory);
            request.setAttribute("data", ls);
            request.setAttribute("lsCategory", lsCategory);
            request.setAttribute("lsBookHistory", lsBookHistory);
            request.getRequestDispatcher("index2.jsp").forward(request, response);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    // <editor-fold defaultstate="collapsed" desc="HttpServlet methods. Click on the + sign on the left to edit the code.">
    /**
     * Handles the HTTP <code>GET</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        processRequest(request, response);
    }

    /**
     * Handles the HTTP <code>POST</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        processRequest(request, response);
    }

    /**
     * Returns a short description of the servlet.
     *
     * @return a String containing servlet description
     */
    @Override
    public String getServletInfo() {
        return "Short description";
    }// </editor-fold>

}

web/component/book.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<a href="BookDetailServlet?id=${book.id}" style="text-decoration: none;color:white;">
    <div style="position:absolute;left:5px">
        <span class="badge bg-primary">${book.latestUpdate}</span>
    </div>
    <img src="asset/img/book/${book.imgName}" style="height:291px;width:194px;" class="card-img-top"  alt="?????">


    <div class="card-body">
        <h5  class="card-title" style = "text-align: center;-webkit-line-clamp: 2;
             -webkit-box-orient: vertical;
             overflow: hidden;
             display: -webkit-box;">${book.name}</h5>
        <!--<div height = "150px" class=" overflow: scroll">-->
        <!--<p class="card-text" style="overflow: scroll">${book.description}</p>-->
        <!--</div>-->
        <!--<a href="#" class="btn btn-primary">Add to cart</a>-->

    </div>
</a>
<span class="info" style="color:white;width:40vw; ">
    <h5 style = "white-space:normal;-webkit-line-clamp: 2;
        -webkit-box-orient: vertical;
        overflow: hidden;
        display: -webkit-box;color:#2E8BE8">${book.name}</h5>
    <p>${book.status}</p>
    <p>Views: ${book.totalView}</p>
    <c:forEach items="${book.allCategory}" var="cate">
        <span class="badge bg-primary">${cate.categoryName}</span>
    </c:forEach>
    <br>
    <p style="
       white-space:normal;
       overflow: hidden;
       text-overflow: ellipsis;
       display: -webkit-box;
       -webkit-box-orient: vertical;
       -webkit-line-clamp: 10;
       ">${book.description}</p>
</span>

web/component/comment.jsp
<%-- 
    Document   : comment
    Created on : Mar 15, 2021, 10:01:51 PM
    Author     : hoang
--%>

<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<script src="asset/js/commentAjax.js"></script>
<style>
    .list-chapter li{
        padding: 6px 40px 6px 10px; background-color: rgba(103,104,105,.3);margin-bottom:25px;border-radius: 5px;
    }
    .list-chapter li .comment-info{
        font-size:0.85em;opacity: 0.5;
    }
</style>
<input style="display:none" id="temp" value="?bookId=${requestScope.book.id}&chapterId=${requestScope.chapter.chapterId}">
<div class="container">
    <div class="card mt-2" style="background: #212529;color:white; ">
        <div class="card-header">
            Comments
        </div>
        <div class="card-body">
            
            <c:choose>
                <c:when test="${sessionScope.user!=null}">
                    <div class="post-comment mb-3">
                        <div accept-charset="Windows-1256" method="post">
                            <div class="post-comment-content" >
                                <textarea id="comment" style="background-color: rgba(103,104,105,.3);width:100%; color:white;border:none;"  rows="5" name="comment">Type your comment here</textarea>
                            </div>
                            <div class="post-comment-submit" style="background-color: #353535; height:40px">
                                <button style="margin:3px 10px 0; color:white;background-color: #36a189;padding:2px 15px; border-radius: 5px;font-weight:700;border-width: 0px;border:none;" onclick="loadComment()">Post Comment</button>
                            </div>
                        </div>
                    </div>
                </c:when>
                <c:otherwise>
                    <div class="post-comment mb-3" style="color:white">
                        You must login to post your comment
                    </div>
                </c:otherwise>
            </c:choose>
            <ul class="list-chapter"style="list-style-type: none;padding-inline-start:0;">
                <div id ="new-comment"></div>
                <c:forEach items="${requestScope.lsComment}" var="comment">
                    <li>
                        <div class="comment">
                            <div class="comment-account">
                                ${comment.account.name}
                            </div>
                            <div class="comment-content mt-2">
                                ${comment.content}
                            </div>
                            <div class="comment-info mt-2" >
                                ${comment.getPostTime()}
                            </div>
                        </div>
                    </li>
                </c:forEach>
            </ul>
        </div>
    </div>
</div>

web/component/footer.jsp
<div id="footer" style="color:white; font-weight: 700;margin-top:15px;background-color: #333">
    <div class="container" style="width:100vw; padding:20px 0">
        <div class="row">
            <div class="col-md-6" style="text-align: center">
                @2021 Hoang Manga - Design by hoangthethief
            </div>
            <div class="col-md-6" style="text-align: center">
                Contact for ads: hoangthanhdinh1@gmail.com
            </div>
        </div>
    </div>
</div>

web/component/navbar.jsp
<%-- 
    Document   : navbar
    Created on : Jan 14, 2021, 9:02:27 PM
    Author     : hoang
--%>

<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%--<%@page contentType="text/html" pageEncoding="UTF-8"%>--%>
<nav class="navbar navbar-expand-lg navbar-light "  style="background-color: rgb(255,128,0)">
    <div class="container">
        <a class="navbar-brand" href="BookServlet">TruyentranhHOANG</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
                <!--                <a class="nav-link active" aria-current="page" href="#">Category</a>-->
                <div class="dropdown">
                    <button class="btn" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
                        Category
                    </button>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton" style="width:70vw; top:45px">
                        <div class="row">
                            <c:forEach items="${requestScope.lsCategory}" var = "category">
                                <div class="col-md-2">
                                    <li><a class="dropdown-item" href="BookWithCategoryServlet?categoryId=${category.categoryId}">${category.categoryName}</a></li>
                                </div>
                            </c:forEach>
                        </div>
                    </ul>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="HistoryServlet">History</a>
            </li>
            <c:if test="${requestScope.admin}">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Web management
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="AdminBookManagement">Book management</a></li>
                    <li><a class="dropdown-item" href="ChartController">Charts</a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
            </li>
            </c:if>
            <li class="nav-item">
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
            </li>
        </ul>
        <form class="d-flex" action="BookSearchServlet">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="search">
            <button class="btn btn-outline-success" type="submit">Search</button>
        </form>

        <c:choose>
            <c:when test="${sessionScope.user != null}">
                <div class="dropdown">
                    <button class="btn" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
                        ${sessionScope.user}
                    </button>
                    <div class="accountDropdown dropdown-menu" aria-labelledby="dropdownMenuButton" style="width:200%;right:0!important;left:auto">
                        <a href="#" class="dropdown-item">Personal page</a>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item">Bookcase</a>
                        <div class="dropdown-divider"></div>
                        <a href="LogoutServlet" class="dropdown-item" style="text-align: center">Log out</a>
                    </div>
                </div>
            </c:when>
            <c:otherwise>
                <form action="login.jsp" method="get">
                    <button class="btn btn-outline-success" type="submit">Login</button>
                </form>
                <form action="register.jsp" method="get">
                    <button class="btn btn-outline-success" type="submit">Register</button>
                </form>
            </c:otherwise>
        </c:choose>
    </div>
</nav>

web/component/reportButton.jsp
<!-- Example single danger button -->
<div class="btn-group">
  <button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Action
  </button>
  <div class="dropdown-menu">
    <a class="dropdown-item" href="#">Action</a>
    <a class="dropdown-item" href="#">Another action</a>
    <a class="dropdown-item" href="#">Something else here</a>
    <div class="dropdown-divider"></div>
    <a class="dropdown-item" href="#">Separated link</a>
  </div>
</div>

web/component/userInfoSidebar.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<div class="side-bar">
  <div class="avatar-profile">
    <img src="asset/img/body/undraw_profile_pic_ic5t.svg" alt="" />
    <h3>${sessionScope.user}</h3>
  </div>
  <div class="management">
    <div class="user-action-menu">
      <ul>
        <li>
          <a href="UserProfileServlet?accountId=${sessionScope.accountId}"
            ><i class="fa fa-home"></i> Home</a
          >
        </li>
        <li>
          <a href="UserBookMarkServlet?accountId=${sessionScope.accountId}">
            <i class="fa fa-bookmark"></i> Book Mark</a
          >
        </li>
        <li>
          <a href="UserHistoryServlet?accountId=${sessionScope.accountId}"
            ><i class="fa fa-history"></i> History</a
          >
        </li>
        <li>
          <a href="UserFollowServlet?accountId=${sessionScope.accountId}"
            ><i class="fa fa-heart"></i> Following</a
          >
        </li>
        <li>
          <a href=""><i class="fa fa-exclamation-triangle"></i> Report</a>
        </li>
        <li><a href="">Request</a></li>
      </ul>
    </div>
  </div>
</div>